name: Build MobileGlues for Android
on: [push, workflow_dispatch]

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_HOME: ${{ github.workspace }}/android-ndk-r27c
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
          unzip android-ndk-r27c-linux.zip

      - name: Create build directory
        run: mkdir -p src/main/cpp/build

      - name: Configure CMake
        run: |
          cd src/main/cpp
          cmake -B build \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-24 \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build MobileGlues
        run: |
          cd src/main/cpp
          cmake --build build --target mobileglues

      - name: Upload 
        uses: actions/upload-artifact@v4
        with:
          name: MobileGlues-Android-so
          path: src/main/cpp/build
